[tools]
ffmpeg = "8.0"
hugo = "0.147.8"
python = "3.14.0"

[tools."asdf:duhow/asdf-yt-dlp"]
version = "2025.09.26"

[tasks.dev]
run = "hugo serve"

[tasks.fetch-yt-thumbnail]
alias = "thumb"
run = "./fetch-yt-thumbnail.sh"
